"$schema" = 'https://starship.rs/config-schema.json'

format = """
$shell\
[](bg:color_darkgreen fg:color_green)\
$directory\
${custom.flox}\
[î‚°](fg:color_darkgreen bg:color_green)\
$git_branch\
$git_status\
[î‚°](fg:color_green bg:color_blue)\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
[î‚°](fg:color_blue bg:color_bg1)\
$docker_context\
$conda\
$time\
[î‚´ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#325e3e'
color_darkgreen = '#26472f'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[shell]
bash_indicator = "ğŸ§"
nu_indicator = "ğŸ’ "
style = "fg:color_fg0 bg:color_darkgreen"
format = '[$indicator ]($style)'
disabled = false

[directory]
style = "fg:color_fg0 bg:color_darkgreen"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ğŸ“„ "
"Downloads" = "ğŸ“¥ "
"Pictures" = "ğŸ–¼ï¸ "
"projects" = "ğŸ’» "
"nix" = "â„ï¸ "

[git_branch]
symbol = "ï˜"
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_green)]($style)'
modified = "â—"
untracked = "â—‹"
staged = "â™¦"
renamed = "âŸ³"
deleted = "âœ•"

[custom.flox]
command = "nu /home/decard/nix/bin/nuScripts/getFloxEnv.nu"
when = "if ((flox envs --active --json | from json | length) > 0) { exit 0 } else { exit 1 }"
style = "bg:color_blue"
format = '[[ â„ï¸ $output ](fg:color_fg0 bg:color_darkgreen)]($style)'
shell = ["nu"]

[bun]
symbol = "ğŸ§…"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[nodejs]
symbol = "ó°™"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = "ğŸ¹"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = "â˜•"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = "ğŸ¯"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = "ğŸ"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = "ğŸ‹"
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
symbol = "ğŸ"
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[ ïº $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ï²](bold fg:color_green)'
error_symbol = '[ï²](bold fg:color_red)'
vimcmd_symbol = '[ï´](bold fg:color_green)'
vimcmd_replace_one_symbol = '[ï´](bold fg:color_purple)'
vimcmd_replace_symbol = '[ï´](bold fg:color_purple)'
vimcmd_visual_symbol = '[ï´](bold fg:color_yellow)'      # vim Ğ²Ğ¸Ğ·ÑƒĞ°Ğ»ÑŒĞ½Ñ‹Ğ¹ Ñ€ĞµĞ¶Ğ¸Ğ¼
